## Libreria Numpy

In [2]:
import numpy as np
print(np.__version__)

1.23.5


In [7]:
lista=[1,2,3,4]
arreglo=np.array(lista)#transforma la lista a un arreglo de numpy
print(arreglo)
arreglo2=arreglo*2
print(arreglo2)
print(type(arreglo))
print(type(lista))

[1 2 3 4]
[2 4 6 8]
<class 'numpy.ndarray'>
<class 'list'>


In [21]:
#hacer una matriz
matriz=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(matriz)
print(matriz.shape)#muestra la forma de la matriz

[[1 2 3]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [28]:
#obtener un elemento de la matriz
print(matriz[1,0])#imprime el elemento de la primera fila y primera columna


3


In [10]:
#uso de arange con numpy
arreglo3=np.arange(0,10,2)#crea un arreglo con valores desde 0 hasta 10 con un paso de 2
print(arreglo3)

[0 2 4 6 8]


In [11]:
#matriz de zeros
matriz_zeros=np.zeros((3,3))#crea una matriz de 3 filas y 3 columnas llena de ceros
print(matriz_zeros)
#matriz de unos
matriz_unos=np.ones((2,4))#crea una matriz de 2 filas y 4 columnas llena de unos
print(matriz_unos)  
#matriz identidad
matriz_identidad=np.eye(4)#crea una matriz identidad de 4x4
print(matriz_identidad) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#matriz aleatoria
matriz_aleatoria=np.random.rand(3,3)#crea una matriz de 3 filas y 3 columnas con valores aleatorios entre 0 y 1
print(matriz_aleatoria)
matriz_aleatoria2=np.random.randint(0,10,(3,3))#crea una matriz de 3 filas y 3 columnas con valores aleatorios enteros entre 0 y 10
print(matriz_aleatoria2)    

[[0.87176661 0.6076207  0.21271267]
 [0.35718694 0.61428222 0.98171392]
 [0.83041105 0.76614724 0.5010161 ]]
[[2 5 4]
 [0 4 8]
 [2 9 3]]


In [15]:
print(np.diag(matriz_identidad)) #obtiene la diagonal de la matriz 
print(matriz_aleatoria2.T) #obtiene la transpuesta de la matriz 


[1. 1. 1. 1.]
[[7 6 5]
 [9 6 3]
 [4 8 9]]


In [18]:
print(matriz_aleatoria2)
matriz_filtrada=matriz_aleatoria2[matriz_aleatoria2>5]#filtra los elementos de la matriz que son mayores a 5
print(matriz_filtrada)

[[7 9 4]
 [6 6 8]
 [5 3 9]]
[7 9 6 6 8 9]


In [19]:
# condiciones en arregles
arreglo4=np.array([1,2,3,4,5,6,7,8,9,10])
#elementos mayores a 5 y menores a 8
arreglo_filtrado=arreglo4[(arreglo4>5) & (arreglo4<8)]
print(arreglo_filtrado)

[6 7]
