**LA LIBRERÍA NUMPY**:
ACT 1 Clase 1

1. Carga y estructuración de datos:

○ Crea un array NumPy con datos financieros simulados (por ejemplo, precios de acciones en diferentes días).

○ Organiza los datos en una matriz de 5x5, donde cada fi la representa una acción y cada columna un día de cotización.

In [6]:
import numpy as np

# Simulación de precios de 5 acciones durante 5 días
precios = np.array([
    [100, 102, 101, 103, 105],
    [50, 49, 51, 52, 50],
    [200, 198, 202, 205, 207],
    [80, 82, 81, 83, 85],
    [120, 121, 119, 122, 124]
])

print("Matriz de precios:")
print(precios)


Matriz de precios:
[[100 102 101 103 105]
 [ 50  49  51  52  50]
 [200 198 202 205 207]
 [ 80  82  81  83  85]
 [120 121 119 122 124]]


In [13]:
#caso sin numpy:
# Simulación de precios de 5 acciones durante 5 días
precioss = [
    [100, 102, 101, 103, 105],
    [50, 49, 51, 52, 50],
    [200, 198, 202, 205, 207],
    [80, 82, 81, 83, 85],
    [120, 121, 119, 122, 124]
]

print("Matriz de precios:")
for fila in precioss:
    print(fila)


Matriz de precios:
[100, 102, 101, 103, 105]
[50, 49, 51, 52, 50]
[200, 198, 202, 205, 207]
[80, 82, 81, 83, 85]
[120, 121, 119, 122, 124]


2. Análisis y transformación de datos:

○ Obtén el promedio, valor máximo y mínimo de cada acción a lo largo del tiempo.

○ Calcula la variación porcentual diaria de cada acción.

○ Aplica funciones matemáticas como logaritmo, exponencial o normalización sobre los datos.

In [ ]:
#Obtén el promedio, valor máximo y mínimo de cada acción a lo largo del tiempo.
promedio = np.mean(precios, axis=1) # axis =1 operar por filas, axis=0 operar por columnas
maximo = np.max(precios, axis=1)
minimo = np.min(precios, axis=1)
#axis=1 operar por filas,Toma cada fila completa: Calcula el promedio / máximo / mínimo de esa fila
print("Promedio por acción:", promedio)
print("Máximo por acción:", maximo)
print("Mínimo por acción:", minimo)


Promedio por acción: [102.2  50.4 202.4  82.2 121.2]
Máximo por acción: [105  52 207  85 124]
Mínimo por acción: [100  49 198  80 119]


In [14]:
#sin numpy hay que aplicar mas codigos y anidarlos
promedios = []
maximos = []
minimos = []

for accion in precioss:
    suma = 0
    max_val = accion[0]
    min_val = accion[0]

    for precio in accion:
        suma += precio
        if precio > max_val:
            max_val = precio
        if precio < min_val:
            min_val = precio

    promedios.append(suma / len(accion))
    maximos.append(max_val)
    minimos.append(min_val)

print("Promedio por acción:", promedios)
print("Máximo por acción:", maximos)
print("Mínimo por acción:", minimos)


Promedio por acción: [102.2, 50.4, 202.4, 82.2, 121.2]
Máximo por acción: [105, 52, 207, 85, 124]
Mínimo por acción: [100, 49, 198, 80, 119]


In [8]:
#Calcula la variación porcentual diaria de cada acción.
variacion_porcentual = np.diff(precios, axis=1) / precios[:, :-1] * 100

print("Variación porcentual diaria:")
print(variacion_porcentual)


Variación porcentual diaria:
[[ 2.         -0.98039216  1.98019802  1.94174757]
 [-2.          4.08163265  1.96078431 -3.84615385]
 [-1.          2.02020202  1.48514851  0.97560976]
 [ 2.5        -1.2195122   2.4691358   2.40963855]
 [ 0.83333333 -1.65289256  2.5210084   1.63934426]]


In [15]:
#sin numpy
variacion_porcentual = []

for accion in precioss:
    variacion_accion = []
    for i in range(1, len(accion)):
        cambio = (accion[i] - accion[i - 1]) / accion[i - 1] * 100
        variacion_accion.append(cambio)
    variacion_porcentual.append(variacion_accion)

print("Variación porcentual diaria:")
for v in variacion_porcentual:
    print(v)


Variación porcentual diaria:
[2.0, -0.9803921568627451, 1.9801980198019802, 1.9417475728155338]
[-2.0, 4.081632653061225, 1.9607843137254901, -3.8461538461538463]
[-1.0, 2.0202020202020203, 1.4851485148514851, 0.975609756097561]
[2.5, -1.2195121951219512, 2.4691358024691357, 2.4096385542168677]
[0.8333333333333334, -1.6528925619834711, 2.5210084033613445, 1.639344262295082]


In [11]:
#Aplica funciones matemáticas como logaritmo, exponencial o normalización sobre los datos.
log_precios = np.log(precios)
exp_precios = np.exp(precios / 100)
normalizados = (precios - precios.min()) / (precios.max() - precios.min())
print("Logaritmo de los precios:")
print(log_precios)
print("Exponencial de los precios:")
print(exp_precios)
print("Precios normalizados:")
print(normalizados)

Logaritmo de los precios:
[[4.60517019 4.62497281 4.61512052 4.63472899 4.65396035]
 [3.91202301 3.8918203  3.93182563 3.95124372 3.91202301]
 [5.29831737 5.28826703 5.3082677  5.32300998 5.33271879]
 [4.38202663 4.40671925 4.39444915 4.41884061 4.44265126]
 [4.78749174 4.79579055 4.77912349 4.80402104 4.82028157]]
Exponencial de los precios:
[[2.71828183 2.77319476 2.74560102 2.80106583 2.85765112]
 [1.64872127 1.63231622 1.66529119 1.68202765 1.64872127]
 [7.3890561  7.24274299 7.53832493 7.76790111 7.92482312]
 [2.22554093 2.27049984 2.24790799 2.29331874 2.33964685]
 [3.32011692 3.35348465 3.28708121 3.38718773 3.45561346]]
Precios normalizados:
[[0.32278481 0.33544304 0.32911392 0.34177215 0.35443038]
 [0.00632911 0.         0.01265823 0.01898734 0.00632911]
 [0.9556962  0.94303797 0.96835443 0.98734177 1.        ]
 [0.19620253 0.20886076 0.20253165 0.21518987 0.2278481 ]
 [0.44936709 0.4556962  0.44303797 0.46202532 0.47468354]]


In [17]:
import math

#sin numpy
log_precios = []

for accion in precioss:
    log_accion = []
    for precio in accion:
        log_accion.append(math.log(precio))
    log_precios.append(log_accion)

print("Logaritmo de precios:")
for fila in log_precios:
    print(fila)





exp_precios = []

for accion in precioss:
    exp_accion = []
    for precio in accion:
        exp_accion.append(math.exp(precio / 100))
    exp_precios.append(exp_accion)


# Buscar mínimo y máximo global
min_global = precios[0][0]
max_global = precios[0][0]

for accion in precios:
    for precio in accion:
        if precio < min_global:
            min_global = precio
        if precio > max_global:
            max_global = precio



# Normalización
normalizados = []

for accion in precioss:
    norm_accion = []
    for precio in accion:
        norm = (precio - min_global) / (max_global - min_global)
        norm_accion.append(norm)
    normalizados.append(norm_accion)

print("Precios normalizados:")
for fila in normalizados:
    print(fila)

Logaritmo de precios:
[4.605170185988092, 4.624972813284271, 4.61512051684126, 4.634728988229636, 4.653960350157523]
[3.912023005428146, 3.8918202981106265, 3.9318256327243257, 3.9512437185814275, 3.912023005428146]
[5.298317366548036, 5.288267030694535, 5.308267697401205, 5.3230099791384085, 5.332718793265369]
[4.382026634673881, 4.406719247264253, 4.394449154672439, 4.418840607796598, 4.442651256490317]
[4.787491742782046, 4.795790545596741, 4.77912349311153, 4.804021044733257, 4.820281565605037]
Precios normalizados:
[np.float64(0.3227848101265823), np.float64(0.33544303797468356), np.float64(0.3291139240506329), np.float64(0.34177215189873417), np.float64(0.35443037974683544)]
[np.float64(0.006329113924050633), np.float64(0.0), np.float64(0.012658227848101266), np.float64(0.0189873417721519), np.float64(0.006329113924050633)]
[np.float64(0.9556962025316456), np.float64(0.9430379746835443), np.float64(0.9683544303797469), np.float64(0.9873417721518988), np.float64(1.0)]
[np.float64(

3. Optimización y selección de datos:

○ Utiliza indexación avanzada para extraer información específi ca, como el rendimiento de una acción en un día determinado.

○ Aplica broadcasting para realizar operaciones sin necesidad de bucles.

In [18]:
precio_especifico = precios[2, 3]
print("Precio acción 3, día 4:", precio_especifico)
precios_dia_2 = precios[:, 1]
print("Precios día 2:", precios_dia_2)


Precio acción 3, día 4: 205
Precios día 2: [102  49 198  82 121]


In [19]:
precios_ajustados = precios * 1.02


4. Comparación con otros métodos:

○ Analiza cómo se podrían realizar estas tareas sin NumPy y compara la efiencia en términos de código y rendimiento computacional.

In [20]:
"""
Comparación con otros métodos de manipulación de datos (sin NumPy)

El análisis y transformación de datos financieros puede realizarse utilizando únicamente estructuras nativas de Python, como listas anidadas, bucles for
y funciones del módulo estándar math. Este enfoque permite resolver correctamente tareas como el cálculo de promedios, valores máximos y mínimos, variaciones
porcentuales y aplicaciones de funciones matemáticas. Sin embargo, estas operaciones requieren múltiples bucles anidados, manejo manual de índices y un mayor
número de líneas de código, lo que incrementa la complejidad, reduce la legibilidad y aumenta la probabilidad de errores lógicos.

Desde el punto de vista del rendimiento computacional, el uso de métodos tradicionales sin NumPy resulta menos eficiente, especialmente cuando se trabaja con
grandes volúmenes de datos. Las operaciones se ejecutan elemento por elemento en el intérprete de Python, lo que implica un mayor tiempo de ejecución y un uso
menos óptimo de la memoria. En contraste, NumPy utiliza implementaciones internas en C altamente optimizadas, lo que permite realizar cálculos vectorizados y
aprovechar mejor los recursos del sistema.

Además, NumPy facilita la escritura de código más conciso y mantenible, ya que muchas operaciones matemáticas y estadísticas se realizan en una sola instrucción,
sin necesidad de bucles explícitos. Esto no solo mejora la eficiencia del desarrollo, sino que también favorece la escalabilidad de las soluciones, aspecto clave
en entornos de análisis financiero en tiempo real.

En conclusión, aunque los métodos tradicionales sin NumPy son funcionales para volúmenes pequeños de datos o fines educativos, NumPy se posiciona como una
herramienta claramente superior en términos de eficiencia, claridad del código y rendimiento computacional, siendo la opción más adecuada para el procesamiento
y análisis de datos numéricos a gran escala.
"""