In [64]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score, KFold


Cargar datos>>Limpiarlos>>Separar los datos X,y>>Escalarlos>>Crear Modelos

In [41]:
data = fetch_california_housing()
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [42]:
print(data.feature_names)
print(data.data)
print('-------------------------')
print(data.target_names)
print(data.target)




['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
-------------------------
['MedHouseVal']
[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [43]:
df = pd.DataFrame(data.data, columns=data.feature_names)
print(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  


In [44]:
df['MedHouseVal'] = data.target
display(df.head())

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422


In [45]:
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']
display(X)
display(y)
print(len(X))

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32


0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

20640


In [46]:
#normalizar las variables
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
len(X_scaled)
display(X_scaled)

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [47]:
display(X_scaled[0])

array([ 2.34476576,  0.98214266,  0.62855945, -0.15375759, -0.9744286 ,
       -0.04959654,  1.05254828, -1.32783522])

In [ ]:
#Separar la data Entrenamiento y Test 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)
print(X_train.shape) #entrenamiento con el 80%
print(X_test.shape) #test con el 20% que corresponde al dato indicado en test_size=0.2

(16512, 8)
(4128, 8)


#crear modelos de regresion lineal

https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares

In [49]:
model=LinearRegression()
model.fit(X_train,y_train)


LinearRegression()

In [57]:
model.score(X_train,y_train)

0.6125511913966952

In [51]:
model.score(X_test,y_test)

0.575787706032451

In [ ]:
model.score(X_scaled,y) # r2

0.606232685199805

In [ ]:
model.coef_ #coeficientes del modelo: y=b0+b1*X1+b2*X2+...+b8*X8

array([ 0.8296193 ,  0.11875165, -0.26552688,  0.30569623, -0.004503  ,
       -0.03932627, -0.89988565, -0.870541  ])

In [29]:
b0=model.intercept_ # b0
b0

2.0685581690891386

In [34]:
#reconstruccion de la ecuación
precio=2.0685581690891386+0.8296193*(2.34476576)+0.11875165*(0.98214266) -0.26552688*(0.62855945)+0.30569623*(-0.15375759)-0.004503*(-0.9744286)-0.03932627*(-0.04959654)-0.89988565*(1.05254828)-0.870541*(-1.32783522)
precio

4.131649819783538

### Modelo arbol de decisiones

In [53]:
from sklearn.tree import DecisionTreeRegressor
model_tree=DecisionTreeRegressor()
model_tree.fit(X_train,y_train)

DecisionTreeRegressor()

In [54]:
model_tree.score(X_train,y_train)

1.0

In [55]:
model_tree.score(X_test,y_test)

0.6123497488757348

In [ ]:
# Como hay mucha diferencia entre X_train y X_test. se dice que hay sobreajuste en el modelo. 
# aprendio demasiado bien del entrenamiento pero no es capaz de obtener tan buenos resultados en el test como los del train

### Random Forest Regressor

In [61]:
from sklearn.ensemble import RandomForestRegressor
model_rf=RandomForestRegressor()
model_rf.fit(X_train,y_train)

RandomForestRegressor()

In [62]:
model_rf.score(X_train,y_train)

0.9738535302172759

In [63]:
model.score(X_test,y_test)

0.575787706032451

In [ ]:
# Validacion cruzada k-fold (dividiendo los datos de entrenemientos y validacion en subconjuntos  mas pequeños)
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,shuffle=True,random_state=43)
kf

KFold(n_splits=5, random_state=43, shuffle=True)

In [72]:
#obtenemos los de r2 para cada fold (para cada una de las vueltas determina un r2 con los sub conjuntos de test del split)
scores=cross_val_score(model,X_train,y_train,cv=kf,scoring='r2')
scores

array([0.62603534, 0.62153645, 0.58636553, 0.61639981, 0.60488889])

In [73]:
#ver estabilidad del modelo
promedio_score=np.mean(scores)
desviacion_score=np.std(scores)
print(promedio_score)
print(desviacion_score)

0.611045202846143
0.014215687762157045
